### ISSUE TITLE
How to stop the circular scrolling?

### ISSUE THREAD

**Issue by GISmanimaran** [natbro/NBInfiniteScroller#2]
I have array for files, i want to load the files in UIScrollView. I have done this but i don't want scroll circularly. Need to stop at when last file reached.

**Comment by natbro** [comment]
In general you should use a normal UIScrollView and not the NBInfiniteScroller if you don't want the circular scrolling - that is what it is providing. Do you have a picture of what you're trying to do you could share?

**Comment by GISmanimaran** [comment]
I am using CoreText in ScrollView, The NBInfiniteScroller is the best way and efficient for me to make that. So, only i am using it. But i just needed the Linear Scrolling only.
![img_0110](https://cloud.githubusercontent.com/assets/6253679/6703442/d20b61d8-cd61-11e4-956c-8bd290d44223.PNG)

![img_0111](https://cloud.githubusercontent.com/assets/6253679/6703443/d20c48c8-cd61-11e4-8704-ffab736a7b67.PNG)

**Comment by natbro** [comment]
i see - unfortunately not super simple to just turn scrolling off. the way it constructs the elements is very convenient with the block `.viewForIndex` vs normal `UIScrollView`s, but you might want to switch to using `UITableView` and a `UITableViewDataSource` of some kind, I think that might be easier. Another option might be to use a different project, https://github.com/nicklockwood/iCarousel.
